export const blogs = [
  {
    id: 1,
    title: "Understanding JavaScript Closures",
    content: "A comprehensive guide to closures in JavaScript...",
    summary: "A deep dive into closures in JavaScript, how they work, and common use cases.",
    author: "John Doe",
    publicationDate: "2024-10-01",
    lastUpdatedDate: "2024-10-15",
    tags: ["JavaScript", "Programming", "Closures"],
    categories: ["Tech", "Tutorials"],
    readingTime: "8 min",
    featuredImage: "/images/analytics.webp",
    keywords: ["JavaScript closures", "closures tutorial", "programming"],
    status: "Published",
    viewsCount: 1200,},
  {
    id: 2,
    title: "CSS Grid vs Flexbox: When to Use Which",
    content: "This post explains the differences between CSS Grid and Flexbox...",
    summary: "An analysis of CSS Grid and Flexbox layout systems, including tips on when to use each.",
    author: "Jane Smith",
    publicationDate: "2024-09-20",
    lastUpdatedDate: "2024-10-05",
    tags: ["CSS", "Web Design", "Grid", "Flexbox"],
    categories: ["Tech", "Design"],
    readingTime: "6 min",
    featuredImage: "/images/analytics.webp",
    keywords: ["CSS Grid", "Flexbox", "web design"],
    status: "Published",
    viewsCount: 980,
  },
  {
    id: 3,
    title: "Introduction to Data Analytics",
    content: "Data analytics involves examining data sets to draw conclusions about the information they contain...",
    summary: "A beginner's guide to data analytics, covering techniques, tools, and the importance of data-driven decision-making.",
    author: "Alice Johnson",
    publicationDate: "2024-08-15",
    lastUpdatedDate: "2024-08-20",
    tags: ["Data Analytics", "Business", "Big Data"],
    categories: ["Tech", "Analytics"],
    readingTime: "10 min",
    featuredImage: "/images/analytics.webp",
    keywords: ["data analytics", "business intelligence", "data-driven"],
    status: "Published",
    viewsCount: 450,
  },
  {
    id: 4,
    title: "Big Data Analysis: Techniques and Tools",
    content: "Big data analysis involves processing and analyzing vast amounts of data to uncover patterns and insights...",
    summary: "Explore the various techniques and tools used in big data analysis, including Hadoop and Spark.",
    author: "Michael Brown",
    publicationDate: "2024-09-05",
    lastUpdatedDate: "2024-09-10",
    tags: ["Big Data", "Hadoop", "Spark"],
    categories: ["Tech", "Data Science"],
    readingTime: "12 min",
    featuredImage: "/images/analytics.webp",
    keywords: ["big data", "data processing", "Hadoop", "Spark"],
    status: "Published",
    viewsCount: 670,
  },
  {
    id: 5,
    title: "Data Visualization: Best Practices",
    content: "Data visualization is a key part of data analytics, allowing analysts to present their findings clearly...",
    summary: "Learn the best practices for creating effective data visualizations that communicate insights clearly.",
    author: "Emily Davis",
    publicationDate: "2024-09-25",
    lastUpdatedDate: "2024-09-30",
    tags: ["Data Visualization", "Business Intelligence"],
    categories: ["Tech", "Design"],
    readingTime: "7 min",
    featuredImage: "/images/analytics.webp",
    keywords: ["data visualization", "best practices", "charts"],
    status: "Published",
    viewsCount: 850,
  },
  {
    id: 6,
    title: "Machine Learning for Data Analysis",
    content: "Machine learning is revolutionizing data analysis, enabling predictions and insights from large datasets...",
    summary: "An introduction to using machine learning techniques for data analysis, including algorithms and applications.",
    author: "Robert Green",
    publicationDate: "2024-10-10",
    lastUpdatedDate: "2024-10-15",
    tags: ["Machine Learning", "Data Analysis"],
    categories: ["Tech", "Data Science"],
    readingTime: "9 min",
    featuredImage: "/images/analytics.webp",
    keywords: ["machine learning", "data analysis", "predictive analytics"],
    status: "Published",
    viewsCount: 1020,
  },
  {
    id: 7,
    title: "Data Ethics: Navigating the Challenges",
    content: "As data becomes more integral to our lives, understanding the ethical implications of data use is crucial...",
    summary: "A discussion on the ethical considerations in data analytics, including privacy and bias.",
    author: "Sophia Turner",
    publicationDate: "2024-10-20",
    lastUpdatedDate: "2024-10-25",
    tags: ["Data Ethics", "Privacy"],
    categories: ["Tech", "Society"],
    readingTime: "5 min",
    featuredImage: "/images/analytics.webp",
    keywords: ["data ethics", "privacy", "bias in data"],
    status: "Published",
    viewsCount: 540,
  },
];
